### ISSUE TITLE
Support for wpa entreprise

### ISSUE THREAD

**Issue by pythops** [pythops/impala#21]

**Comment by MrRazamataz** [comment]
Currently, to connect, you can do it manually. Create a file here `/var/lib/iwd/NETWORK-NAME.8021x` replacing `NETWORK-NAME` with the SSID. Then, inside it, fill in these details:
```toml
[Security]
EAP-Method=PEAP
EAP-Identity=anonymous
EAP-PEAP-Phase2-Method=MSCHAPV2
EAP-PEAP-Phase2-Password=put your password here
EAP-PEAP-Phase2-Identity=put your username here

[Settings]
AutoConnect=true
```
